[bot]
name = "RSS_News"
environment = "dev"
email = "arnoldt2009@gmail.com"

[bot.urls]
websites = [
    "https://thehackernews.com",
    "https://darkreading.com",
    "https://hackercombat.com",
    "https://tomriha.com",
    "https://realpython.com",
    "https://hackernoon.com",
    "https://theverge.com",
    "https://thecyberwire.com",
    "https://lifehacker.com",
    "https://wired.com",
    "https://mashable.com",
    "https://techcrunch.com",
    "https://9to5mac.com",
    "https://droid-life.com",
    "https://thenextweb.com",
    "https://macworld.com",
    "https://petapixel.com",
    "https://geektyrant.com",
    "https://npr.org",
    "https://nerdist.com",
    "https://vox.com",
    "https://themarginalian.org",
    "https://fstoppers.com",
    "https://aljazeera.com",
    "https://inc.com",
    "https://businessinsider.com",
    "https://404media.co"
]

[server]
host = ""
port = ""
ssl = ""

[database]
url = ""
name = ""
username = ""
passsword = ""
